<?xml version="1.0" encoding="utf-8"?><Database Name="PortalEdu" Class="PortalDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=PortalEdu;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PortalEduConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Alumno" Member="Alumno">
    <Type Name="Alumno">
      <Column Name="IdAlumno" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="apellido" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="fecha_n" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="genero" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Alumno_CursoAlumno" Member="CursoAlumno" ThisKey="IdAlumno" OtherKey="IdAlumno" Type="CursoAlumno" />
      <Association Name="Alumno_Pagos" Member="Pagos" ThisKey="IdAlumno" OtherKey="IdAlumno" Type="Pagos" />
      <Association Name="Usuario_Alumno" Member="Usuario" ThisKey="idUsuario" OtherKey="IdUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CursoAlumno" Member="CursoAlumno">
    <Type Name="CursoAlumno">
      <Column Name="IdCurso_Alumno" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdCurso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdAlumno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CursoAlumno_Notas" Member="Notas" ThisKey="IdCurso_Alumno" OtherKey="idCursoAlumno" Type="Notas" />
      <Association Name="Alumno_CursoAlumno" Member="Alumno" ThisKey="IdAlumno" OtherKey="IdAlumno" Type="Alumno" IsForeignKey="true" />
      <Association Name="Cursos_CursoAlumno" Member="Cursos" ThisKey="IdCurso" OtherKey="IdCurso" Type="Cursos" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cursos" Member="Cursos">
    <Type Name="Cursos">
      <Column Name="IdCurso" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Recursos" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Costo" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="idTemario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idDocente" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Cursos_CursoAlumno" Member="CursoAlumno" ThisKey="IdCurso" OtherKey="IdCurso" Type="CursoAlumno" />
      <Association Name="Cursos_Pagos" Member="Pagos" ThisKey="IdCurso" OtherKey="IdCurso" Type="Pagos" />
      <Association Name="Docentes_Cursos" Member="Docentes" ThisKey="idDocente" OtherKey="IdDocente" Type="Docentes" IsForeignKey="true" />
      <Association Name="Temario_Cursos" Member="Temario" ThisKey="idTemario" OtherKey="IdTema" Type="Temario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Docentes" Member="Docentes">
    <Type Name="Docentes">
      <Column Name="IdDocente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="apellido" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="fecha_n" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="genero" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Docentes_Cursos" Member="Cursos" ThisKey="IdDocente" OtherKey="idDocente" Type="Cursos" />
      <Association Name="Usuario_Docentes" Member="Usuario" ThisKey="idUsuario" OtherKey="IdUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Notas" Member="Notas">
    <Type Name="Notas">
      <Column Name="IdNota" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nota" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="idCursoAlumno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CursoAlumno_Notas" Member="CursoAlumno" ThisKey="idCursoAlumno" OtherKey="IdCurso_Alumno" Type="CursoAlumno" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pagos" Member="Pagos">
    <Type Name="Pagos">
      <Column Name="IdPago" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdCurso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdAlumno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Alumno_Pagos" Member="Alumno" ThisKey="IdAlumno" OtherKey="IdAlumno" Type="Alumno" IsForeignKey="true" />
      <Association Name="Cursos_Pagos" Member="Cursos" ThisKey="IdCurso" OtherKey="IdCurso" Type="Cursos" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Temario" Member="Temario">
    <Type Name="Temario">
      <Column Name="IdTema" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tema" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="Temario_Cursos" Member="Cursos" ThisKey="IdTema" OtherKey="idTemario" Type="Cursos" />
    </Type>
  </Table>
  <Table Name="dbo.Usuario" Member="Usuario">
    <Type Name="Usuario">
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Usuario" Member="Usuario1" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="correo" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="contraseña" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="tipo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Usuario_Alumno" Member="Alumno" ThisKey="IdUsuario" OtherKey="idUsuario" Type="Alumno" />
      <Association Name="Usuario_Docentes" Member="Docentes" ThisKey="IdUsuario" OtherKey="idUsuario" Type="Docentes" />
    </Type>
  </Table>
  <Function Name="dbo.ModificaAlumno" Method="ModificaAlumno">
    <Parameter Name="idAlumno" Type="System.Int32" DbType="Int" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="apellido" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="fecha_n" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="genero" Type="System.Char" DbType="Char(1)" />
    <ElementType Name="ModificaAlumnoResult">
      <Column Name="Mensaje" Type="System.String" DbType="VarChar(31) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ModificaCursos" Method="SP_ModificaCursos">
    <Parameter Name="idCurso" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Recursos" Parameter="recursos" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Costo" Parameter="costo" Type="System.Decimal" DbType="Money" />
    <ElementType Name="SP_ModificaCursosResult">
      <Column Name="Mensaje" Type="System.String" DbType="VarChar(31) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ModificaNotas" Method="SP_ModificaNotas">
    <Parameter Name="idNota" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nota" Parameter="nota" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Estado" Parameter="estado" Type="System.String" DbType="VarChar(15)" />
    <ElementType Name="SP_ModificaNotasResult">
      <Column Name="Mensaje" Type="System.String" DbType="VarChar(31) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ModificaTemarios" Method="SP_ModificaTemarios">
    <Parameter Name="idTema" Type="System.Int32" DbType="Int" />
    <Parameter Name="Tema" Parameter="tema" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(200)" />
    <ElementType Name="SP_ModificaTemariosResult">
      <Column Name="Mensaje" Type="System.String" DbType="VarChar(31) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ModificaUsuario" Method="SP_ModificaUsuario">
    <Parameter Name="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="Usuario" Parameter="usuario" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="correo" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="contraseña" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="tipo" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_ModificaUsuarioResult">
      <Column Name="Mensaje" Type="System.String" DbType="VarChar(31) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ModificaDocente" Method="SP_ModificaDocente">
    <Parameter Name="idDocentes" Type="System.Int32" DbType="Int" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="apellido" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="fecha_n" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="genero" Type="System.Char" DbType="Char(1)" />
  </Function>
</Database>